server:
  port: 8092

spring:
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  datasource:
    url: jdbc:postgresql://localhost:5432/hust_course_mngt
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  services:
    subject-service: http://localhost:9000/subject-service/hust/subjects  

build:
  version: 1.0    

# spring.datasource.url=jdbc:postgresql://localhost:5432/hust_course_mngt
# spring.datasource.username=postgres
# spring.datasource.password=admin

# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=update

# eureka client
# eureka.instance.client.serverUrl.defaultZone=http://localhost:8761/eureka/
# end
