server:
  port: 8093

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hust_grade_mngt
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    # hibernate:
    #   ddl-auto: update
    show-sql: true    

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true    

endpoints:
  shutdown:
    enabled: true   

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serverUrl:
      defaultZone: http://localhost:8761/eureka/
      
app-configs:
  version: 1.8


# eureka client
# eureka:
#   instance:
#     client:
#       serverUrl:
#         defaultZone: http://localhost:8761/eureka/
# end
